service: GoLambdaExample
frameworkVersion: '3'

provider:
  name: aws
  architecture: arm64
  runtime: provided.al2
  apiGateway:
    minimumCompressionSize: 1024
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  environment:
    USER_TABLE_NAME: ${self:custom.UserTable.name}
  iam:
    role:
      statements:
        - ${file(serverless/iam/UserTableIAM.yml):UserTableIAM}

plugins:
 - serverless-go-plugin

package:
  individually: true
  include:
    - src/createAWSResError.go
    - src/validationFunctions.go

functions:
  signup:
    handler: src/signup.go
    events:
      - http:
          method: POST
          path: user/signup
          cors: true
resources:
  Resources:
    UserTable: ${file(serverless/resources/UserTable.yml):UserTable}

    # This response is needed for custom authorizer failures cors support
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'

custom:
  go:
    supportedRuntimes:
      - provided.al2
    cmd: GOOS=linux GOARCH=arm64 go build -ldflags="-s -w"' # compile command

  UserTable:
    name: !Ref UserTable
    arn: !GetAtt UserTable.Arn

  bundle:
    linting: true
